### ISSUE TITLE
FROM requests

### ISSUE THREAD

**Issue by tyler36** [vinkla/recaptcha#5]
Thanks for taking the time to update the package but I seem to be having an issue.

Just noticed that my network tab is full of requests every second.
![clipboard02](https://cloud.githubusercontent.com/assets/7234392/26566870/7921039e-4531-11e7-8f1c-0116fdd4ab42.jpg)

Under the Header requests it show:
```
200 Request has been forbidden by antivirus
```

The package seems to work fine (I can validate etc.). Not sure if there has been a recent google update that broke something, my AV broke something in their last update or your part of secret organisation to train an elite team of hacking Alaskan bears? 

Any ideas?

**Comment by vinkla** [comment]
Not sure what your issue are to be honest. If the validation works with reCAPTCHA it is probably something in your code. I don't recognise the request data from your screenshot. It is probably the bears.

**Comment by tyler36** [comment]
Thanks for the feedback. If if figure something out, I'll let you know.
